FROM condaforge/mambaforge
LABEL MAINTAINER="Kyle Wilcox <kyle@axds.co>"

RUN mamba create -n tools --yes conda-lock && \
    mamba clean --all --yes

COPY reqs.yml /tmp/reqs.yml
RUN /opt/conda/envs/tools/bin/conda-lock \
        --conda=mamba \
        --mamba \
        -p linux-64 \
        -f /tmp/reqs.yml \
        --lockfile /tmp/conda-lock.yml

RUN mamba create -n locked --yes --file /tmp/conda-lock.yml && \
    mamba clean --all --yes
